# Generated by Django 2.2.16 on 2022-05-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220504_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте изображение', upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
